"""Add file_hash with unique constraint to pagos table

Revision ID: 335b7bb5055d
Revises: b845f1d9ce29
Create Date: 2026-03-06 18:14:35.359466

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '335b7bb5055d'
down_revision: Union[str, None] = 'b845f1d9ce29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pagos_file_hash', table_name='pagos')
    op.create_index(op.f('ix_pagos_file_hash'), 'pagos', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_file_hash'), table_name='pagos')
    op.create_index('ix_pagos_file_hash', 'pagos', ['file_hash'], unique=False)
    # ### end Alembic commands ###