"""empty message

Revision ID: 7f45890161ff
Revises: 20260404_add_banco_emisor_column
Create Date: 2026-04-07 16:08:23.968061

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '7f45890161ff'
down_revision: Union[str, None] = '20260404_add_banco_emisor_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###