"""sincronizacion_inicial

Revision ID: b845f1d9ce29
Revises: 20260130_add_file_hash_column
Create Date: 2026-03-06 09:54:08.096597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b845f1d9ce29'
down_revision: Union[str, None] = '20260130_add_file_hash_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_clientes_cedula'), 'clientes', type_='unique')
    op.create_index(op.f('ix_clientes_cedula'), 'clientes', ['cedula'], unique=True)
    op.create_index(op.f('ix_clientes_telefono'), 'clientes', ['telefono'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clientes_telefono'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cedula'), table_name='clientes')
    op.create_unique_constraint(op.f('uq_clientes_cedula'), 'clientes', ['cedula'], postgresql_nulls_not_distinct=False)
    op.alter_column('clientes', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###